version: "3"

services:
  main:
    container_name: remote-container-sample
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/work
    stdin_open: true
